### ISSUE TITLE
undefined method `transport'

### ISSUE THREAD

**Issue by wackazong** [versatica/OverSIP#64]
I have a strange issue. When I connect with sipML5 from a web browers to the oversip websocket server via www on port 10443 all is fine if the SIP server I am contacting is not on the same server as oversip. If it is, then I get this error:

Dec 11 18:08:01 ip-172-31-38-164 oversip[22840]:  ERROR: <WsSipApp> undefined method `transport' for #<OverSIP::SIP::RFC3263::MultiTargets:0x000000030e0d78> (NoMethodError)#012/usr/local/rvm/gems/ruby-2.1.0/gems/oversip-2.0.0/lib/oversip/sip/client.rb:374:in`use_target'#012/usr/local/rvm/gems/ruby-2.1.0/gems/oversip-2.0.0/lib/oversip/sip/client.rb:345:in `try_next_target'#012/usr/local/rvm/gems/ruby-2.1.0/gems/oversip-2.0.0/lib/oversip/sip/client.rb:328:in`rfc3263_succeeded'#012/usr/local/rvm/gems/ruby-2.1.0/gems/oversip-2.0.0/lib/oversip/sip/client.rb:255:in `check_dns_cache'

**Comment by wackazong** [comment]
This only occurs when enabling NAPTR and SRV record support. NAPTR and SRV were enabled in the other proxy configs. Misunderstood the proxies.conf. If you enable NAPTR and SRV it should fail.

Dec 12 18:44:30 ip-172-31-38-164 oversip[4284]:  DEBUG: <SIP WSS-Tunnel IPv4 server> connection from the TLS tunnel 127.0.0.1:54904

Dec 12 18:44:30 ip-172-31-38-164 oversip[4284]:  DEBUG: <SIP WSS-Tunnel IPv4 server> running OverSIP::WebSocketEvents.on_connection()...

Dec 12 18:44:30 ip-172-31-38-164 oversip[4284]:  DEBUG: <HTTP WS Request> replying 101 "Switching Protocols"

Dec 12 18:44:30 ip-172-31-38-164 oversip[4284]:  DEBUG: <WsFraming> received text frame: FIN=true, RSV1-3=false/false/false, payload_length=772

Dec 12 18:44:30 ip-172-31-38-164 oversip[4284]:  DEBUG: <WsSipApp> received WS message: type=text, length=772

Dec 12 18:44:30 ip-172-31-38-164 oversip[4284]:   INFO: <SipEvents> [user] REGISTER from sip:UViljwt0hE7dWoB0Pt7MY@staging.sipheadstore.com (UA: IM-client/OMA1.0 sipML5-v1.2014.04.18) to sip:staging.sipheadstore.com via WSS 172.31.44.137 : 62314

Dec 12 18:44:30 ip-172-31-38-164 oversip[4284]:  DEBUG: <SIP Request K2GD8TyylORkFOUIB53fQ8ca37UPc6pc> applying outgoing Outbound support

Dec 12 18:44:30 ip-172-31-38-164 oversip[4284]:  DEBUG: <RFC3263 K2GD8TyylORkFOUIB53fQ8ca37UPc6pc> DNS NAPTR succeeded for 'staging.sipheadstore.com'

Dec 12 18:44:30 ip-172-31-38-164 oversip[4284]:  DEBUG: <RFC3263 K2GD8TyylORkFOUIB53fQ8ca37UPc6pc> DNS SRV succeeded for '_sip._udp.staging.sipheadstore.com'

Dec 12 18:44:30 ip-172-31-38-164 oversip[4284]:  DEBUG: <RFC3263 K2GD8TyylORkFOUIB53fQ8ca37UPc6pc> DNS A succeeded for domain 'edge1.staging.sipheadstore.com'

Dec 12 18:44:30 ip-172-31-38-164 oversip[4284]:  DEBUG: <RFC3263 K2GD8TyylORkFOUIB53fQ8ca37UPc6pc> DNS A succeeded for domain 'edge2.staging.sipheadstore.com'

Dec 12 18:44:30 ip-172-31-38-164 oversip[4284]:  DEBUG: <Proxy proxy_out K2GD8TyylORkFOUIB53fQ8ca37UPc6pc> DNS result has multiple values, randomizing

Dec 12 18:44:30 ip-172-31-38-164 oversip[4284]:  DEBUG: <Proxy proxy_out K2GD8TyylORkFOUIB53fQ8ca37UPc6pc> trying target 1 of 2: [#<struct OverSIP::SIP::RFC3263::Target transport=:udp, ip="54.194.12.167", ip_type=:ipv4, port=5060>]

Dec 12 18:44:30 ip-172-31-38-164 oversip[4284]:  DEBUG: <OutboundMangling module> performing Contact mangling (adding ;ov-ob Outbound param) for SIP Request K2GD8TyylORkFOUIB53fQ8ca37UPc6pc

Dec 12 18:44:30 ip-172-31-38-164 oversip[4284]: NOTICE: <Proxy proxy_out K2GD8TyylORkFOUIB53fQ8ca37UPc6pc> LOG:

Dec 12 18:44:30 ip-172-31-38-164 oversip[4284]: NOTICE: <Proxy proxy_out K2GD8TyylORkFOUIB53fQ8ca37UPc6pc> target [#<struct OverSIP::SIP::RFC3263::Target transport=:udp, ip="54.194.12.167", ip_type=:ipv4, port=5060>]

Dec 12 18:44:30 ip-172-31-38-164 oversip[4284]:  ERROR: <launcher (master)> error raised during event loop and rescued by EM.error_handler:

Dec 12 18:44:30 ip-172-31-38-164 oversip[4284]:  ERROR: <launcher (master)> undefined method `transport' for #<OverSIP::SIP::RFC3263::MultiTargets:0x000000035d7b60> (NoMethodError)#012/usr/local/rvm/gems/ruby-2.1.0/gems/oversip-2.0.0/lib/oversip/sip/client.rb:376:in `use_target'#012/usr/local/rvm/gems/ruby-2.1.0/gems/oversip-2.0.0/lib/oversip/sip/client.rb:345:in `try_next_target'#012/usr/local/rvm/gems/ruby-2.1.0/gems/oversip-2.0.0/lib/oversip/sip/client.rb:328:in `rfc3263_succeeded'#012/usr/local/rvm/gems/ruby-2.1.0/gems/oversip-2.0.0/lib/oversip/sip/client.rb:281:in `block in do_dns'

Dec 12 18:44:35 ip-172-31-38-164 oversip[4284]:  DEBUG: <NIST K2GD8TyylORkFOUIB53fQ8ca37UPc6pc> no final response within 5 seconds => 100

Dec 12 18:44:35 ip-172-31-38-164 oversip[4284]:  DEBUG: <SIP Request K2GD8TyylORkFOUIB53fQ8ca37UPc6pc> replying 100 "I'm alive"

Dec 12 18:44:35 ip-172-31-38-164 oversip[4284]:  DEBUG: <WsFraming> sending text frame: payload_length=417
